

# Message for base rotation
# range from -50 to 50
# full clockwise rotation is 50
# full counter-clockwise rotation is -50
float64 base

# Message for link1 angle_movement
# range from -50 to 50
# full open is 50
# full close (or close to it ) is -50
float64 link1

# Message for link2 angle_movement
# range from -50 to 50
# full clockwise rotation is 50
# full counter-clockwise rotation is -50
# full open is 50
# full close (or close to it ) is -50
float64 link2

# Message for d1 movement
# range from -100 to 100
# facing up is 100
# facing down is -100
float64 d1

# Message for d2 movement
# range from -100 to 100
# facing up is 100
# facing down is -100
float64 d2

# Message for claw opening/closing
# range from -50 to 50
# full opening is 50
# full closing is -50
float64 claw

